spring:
  application:
    name: recommendation-service
  datasource:
    url: ${RECOMMENDATION_DB_URL}
    username: ${RECOMMENDATION_DB_USER}
    password: ${RECOMMENDATION_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVER}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    service-url:
      defaultZone: ${SERVER_URL}

server:
  port: ${RECOMMENDATION_PORT}
