spring:
  application:
    name: recommendation-service
  datasource:
    url: ${RECOMMENDATION_DB_URL}
    username: ${RECOMMENDATION_DB_USER}
    password: ${RECOMMENDATION_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

    eureka:
      client:
        service-url:
          defaultZone: ${SERVER_URL}

server:
  port: ${RECOMMENDATION_PORT}
