auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

limits_config:
  reject_old_samples_max_age: 168h
  ingestion_rate_strategy: global

schema_config:
  configs:
    - from: 2025-01-18
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: loki_index_
        period: 24h

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/tsdb-index
    cache_location: /loki/tsdb-cache
  filesystem:
    directory: /loki/chunks

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100
        ttl: 30m
  cache_results: true
  parallelise_shardable_queries: true

compactor:
  working_directory: /loki/compactor
