spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/** ,/api/follows/**,/api/users/**

        - id: feed-service
          uri: lb://feed-service
          predicates:
            - Path=/api/feeds/**

        - id: area-service
          uri: lb://area-service
          predicates:
            - Path=/api/areas/**

        - id: coupon-service
          uri: lb://coupon-service
          predicates:
            - Path=/api/coupons/**

        - id: interaction-service
          uri: lb://interaction-service
          predicates:
            - Path=/api/interaction/**, /api/comments/**, /api/likes/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notification/**

        - id: recommendation-service
          uri: lb://recommendation-service
          predicates:
            - Path=/api/recommendation/**

      discovery:
        locator:
          enabled: true

server:
  port: 19091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

service:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
