spring:
  datasource:
    url: ${FEED_DB_URL}
    username: ${FEED_DB_USER}
    password: ${FEED_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

    eureka:
      client:
        service-url:
          defaultZone: ${SERVER_URL}

server:
  port: ${FEED_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    health:
      show-details: always