spring:
  application:
    name: feed-service

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: ${FEED_DB_URL}
    username: ${FEED_DB_USER}
    password: ${FEED_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

aws:
  s3:
    access-key: ${Access key ID}
    secret-key: ${Secret access key}
    bucket: link-eleven-bucket
    region: ap-northeast-2
    stack:
      auto: false

service:
  jwt:
    secret-key: ${JWT_SECRET_KEY}

server:
  port: 19093
