spring:
  application:
    name: interaction

  datasource:
    url: ${INTERACTION_DB_URL}
    username: ${INTERACTION_DB_USER}
    password: ${INTERACTION_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

    eureka:
      client:
        service-url:
          defaultZone: http://localhost:19090/eureka/

  kafka:
    bootstrap-servers: localhost:29092,localhost:29093,localhost:29094
    properties:
      schema.registry.url: http://localhost:28081
      retry:
        enable: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true
    listener:
      try:
        topic:
          enabled: true

server:
  port: 19094
