spring:
  datasource:
    url: ${INTERACTION_DB_URL}
    username: ${INTERACTION_DB_USER}
    password: ${INTERACTION_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

    eureka:
      client:
        service-url:
          defaultZone: http://localhost:19090/eureka/

server:
  port: 19094
